export * from './types.js'
export * from './checksum.js'
export * from './canonical-jsonl.js'
export * from './curation.js'
export * from './registry.js'
export * from './pipeline.js'
export { AdapterRegistry, defaultAdapterRegistry } from './adapters.js'
export type { AdapterKind, AdapterContext, UpstreamAdapter as IngestionAdapter } from './adapters.js'
export * from './connectors/filesystem.js'
export * from './connectors/http.js'

// Universal Corpus Registry
export * from './registry/index.js'
export * from './identity/index.js'
export * from './quality/index.js'
export * from './alignment/index.js'
export * from './materialization/index.js'
export * from './contribution/index.js'
export * from './depth/index.js'

// Upstream Engine
export * from './upstream/types.js'
export * from './upstream/adapter-registry.js'
export * from './upstream/recipe-resolver.js'
export * from './upstream/planner.js'
export * from './upstream/manifest.js'
export * from './upstream/runner.js'
