import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { UniversalCorpusRegistry } from '../registry/universal-registry.js'
import { MetadataEditionQueue } from './edition-queue.js'
import { MaterializationAuditor } from './materialization-auditor.js'
import type { EditionMaterializationResult, EditionRecordCount, MaterializationEngineSummary, SourceContributionRecord } from './types.js'

/** Discovers retained materialized rows. It never manufactures records for queue items. */
export class EditionMaterializer {
  private readonly rootDir: string
  private readonly registry: UniversalCorpusRegistry
  private readonly queue: MetadataEditionQueue
  constructor(rootDir: string = process.cwd()) { this.rootDir=rootDir; this.registry=new UniversalCorpusRegistry(path.join(rootDir,'config')); this.queue=new MetadataEditionQueue(rootDir) }
  async executeMaterialization(options:{dryRun?:boolean}={}) {
    await this.registry.loadAll(); const items=await this.queue.buildQueue();
    if(options.dryRun) { const dryResults: EditionMaterializationResult[] = items.map(i=>({editionId:i.editionId,workId:i.workId,traditionId:i.traditionId,status:'REMOTE_READY',records:0,bytes:0,retrievedAt:new Date().toISOString(),sourceId:i.sourceCandidates[0]??'unknown-source',endpointId:i.endpointCandidates[0]??'unknown-endpoint',adapterId:'discovery-only',provenance:{requestedUrl:'',resolvedUrl:'',retrievedAt:new Date().toISOString()}})); return { results:dryResults, recordCounts:[], summary:{schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),totalEditions:this.registry.getEditions().length,metadataOnlyBefore:items.length,materializedNew:0,full:0,partial:0,metadataOnly:items.length,authRequired:0,rateLimited:0,manualOnly:0,sourceUnavailable:0,failed:0,recordBearingEditions:0,materializationPercent:0,canonicalPositionsBefore:0,canonicalPositionsAfter:0,editionRecordsBefore:0,editionRecordsAfter:0,languageRecords:0,sourceWitnesses:0} as MaterializationEngineSummary, sourceContributions:[] as SourceContributionRecord[] } }
    const audit=await new MaterializationAuditor(this.rootDir).runAudit(); const byId=new Map(audit.auditRecords.map(r=>[r.editionId,r])); const now=new Date().toISOString();
    const results:EditionMaterializationResult[]=items.map(i=>{const r=byId.get(i.editionId)!;const ep=r.endpointIds[0]?this.registry.resolveEndpoint(r.endpointIds[0]):undefined;const url=ep?.url??ep?.repoUrl??ep?.baseUrl??`registry:${i.editionId}`;return{editionId:i.editionId,workId:i.workId,traditionId:i.traditionId,status:r.granularState??'NO_RECORD_DATA' as any,records:r.normalizedRecords,bytes:r.rawBytes,sourceSha256:r.rawSha256,retrievedAt:now,sourceId:r.sourceIds[0]??'unknown-source',endpointId:r.endpointIds[0]??'unknown-endpoint',adapterId:'discovery-only',provenance:{requestedUrl:url,resolvedUrl:url,retrievedAt:now,sourceSha256:r.rawSha256}}});
    const recordCounts:EditionRecordCount[]=audit.auditRecords.map(r=>({editionId:r.editionId,workId:r.workId,language:r.language,rawRecords:r.parsedRecords,parsedRecords:r.parsedRecords,normalizedRecords:r.normalizedRecords,canonicalPositions:r.canonicalRecords,editionRecords:r.indexedRecords,materializationState:r.granularState??'NO_RECORD_DATA' as any})); const s=audit.summary; const summary:MaterializationEngineSummary={schemaVersion:'1.0.0',generatedAt:s.generatedAt,totalEditions:s.totalEditions,metadataOnlyBefore:items.length,materializedNew:0,full:s.full,partial:s.partial,metadataOnly:s.metadataOnly,authRequired:0,rateLimited:0,manualOnly:0,sourceUnavailable:0,failed:0,recordBearingEditions:s.recordBearingEditions,materializationPercent:s.materializationPercent,canonicalPositionsBefore:0,canonicalPositionsAfter:0,editionRecordsBefore:0,editionRecordsAfter:audit.auditRecords.reduce((n,r)=>n+r.indexedRecords,0),languageRecords:new Set(audit.auditRecords.filter(r=>r.normalizedRecords>0).map(r=>r.language)).size,sourceWitnesses:new Set(audit.auditRecords.flatMap(r=>r.sourceIds)).size}; return {results,recordCounts,summary,sourceContributions:audit.sourceContributions}
  }
  async writeAllMaterializationArtifacts(outDir=path.join(this.rootDir,'dist'),options:{dryRun?:boolean}={}) { await mkdir(outDir,{recursive:true}); const queue=await this.queue.buildQueue(); const r=await this.executeMaterialization(options); await writeFile(path.join(outDir,'metadata-edition-queue.json'),JSON.stringify({schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalQueueItems:queue.length,queue},null,2)+'\n'); await writeFile(path.join(outDir,'edition-record-counts.json'),JSON.stringify({schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalEditions:r.recordCounts.length,records:r.recordCounts},null,2)+'\n'); await writeFile(path.join(outDir,'materialization-summary.json'),JSON.stringify(r.summary,null,2)+'\n'); await writeFile(path.join(outDir,'source-contribution-report.json'),JSON.stringify({schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalSources:r.sourceContributions.length,sources:r.sourceContributions},null,2)+'\n') }
}
