import { createRequire } from 'node:module'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'
import { UniversalCorpusRegistry } from '../registry/universal-registry.js'
import type { EditionMaterializationRecord, EditionMaterializationStatus, ZeroRecordEdition, RecordReconciliationRecord, WorkLanguageMaterializationRecord, CanonicalRecordOwnershipRecord, SourceContributionRecord, EditionMaterializationSummary, CorpusGrowthReport } from './types.js'
const require = createRequire(import.meta.url)
const scalar = (db: any, sql: string, ...args: unknown[]) => Number((db.prepare(sql).get(...args) as { c: number }).c)

/** Truthful materialization audit: only retained SQLite rows count as materialized or measured. */
export class MaterializationAuditor {
  private readonly rootDir: string
  private readonly registry: UniversalCorpusRegistry
  constructor(rootDir: string = process.cwd()) { this.rootDir = rootDir; this.registry = new UniversalCorpusRegistry(path.join(rootDir, 'config')) }
  async runAudit() {
    const dbPath = path.join(this.rootDir, 'dist/corpus.sqlite')
    if (!existsSync(dbPath)) throw new Error(`FAIL-CLOSED: ${dbPath} is required for materialization audit`)
    const db = new (require('node:sqlite').DatabaseSync)(dbPath)
    await this.registry.loadAll(); const editions = this.registry.getEditions(); const works = this.registry.getWorks(); const sources = this.registry.getSources(); const endpoints = this.registry.getEndpoints()
    const rows = db.prepare(`SELECT edition_id, work_id, source_id, language, COUNT(*) records, SUM(length(text)) bytes, COUNT(DISTINCT passage_id) canonical_records, COUNT(*) - SUM(CASE WHEN normalized_text_hash IS NULL OR normalized_text_hash='' THEN 1 ELSE 0 END) hashed FROM contents WHERE edition_id IS NOT NULL GROUP BY edition_id,work_id,source_id,language`).all() as any[]
    const byEdition = new Map<string, any[]>(); for (const row of rows) byEdition.set(row.edition_id, [...(byEdition.get(row.edition_id) ?? []), row])
    const jobs = new Map<string, any>(); const manifestPath = path.join(this.rootDir, 'dist/upstream-sync-manifest.json')
    if (existsSync(manifestPath)) try { for (const job of (JSON.parse(await readFile(manifestPath, 'utf8')).jobs ?? [])) jobs.set(String(job.id), job) } catch { /* database truth remains authoritative */ }
    const auditRecords: EditionMaterializationRecord[] = []; const zeroRecordEditions: ZeroRecordEdition[] = []; const recordReconciliations: RecordReconciliationRecord[] = []
    const reason = (ed: any) => byEdition.has(ed.id) ? undefined : (endpoints.some(e => e.workId === ed.workId) ? 'NO_RECORD_DATA' : 'NO_MATERIALIZATION_PIPELINE')
    for (const ed of editions) {
      const er = byEdition.get(ed.id) ?? []; const recordCount = er.reduce((n,r)=>n+Number(r.records),0); const canonicalRecords = er.reduce((n,r)=>n+Number(r.canonical_records),0); const eps = endpoints.filter(e=>e.workId===ed.workId&&(!e.editionId||e.editionId===ed.id)); const sourceIds=[...new Set(er.map(r=>r.source_id).filter(Boolean))]; const hashOk=recordCount>0&&er.every(r=>Number(r.hashed)===Number(r.records)); const status: EditionMaterializationStatus=recordCount?'FULL':'METADATA_ONLY'
      auditRecords.push({ editionId:ed.id, workId:ed.workId, traditionId:this.registry.resolveWork(ed.workId).traditionId, editionType:ed.editionType, language:ed.language, script:ed.script, sourceIds, endpointIds:eps.map(e=>e.id), recipeIds:[], adapterIds:[], registryStatus:'REGISTERED', executionStatus:eps.length?'READY':'PENDING', acquisitionStatus:jobs.get(eps[0]?.id)?.status??(recordCount?'LOCAL_CACHE':'UNCONFIGURED'), rawBytes:er.reduce((n,r)=>n+Number(r.bytes??0),0), parsedRecords:recordCount, normalizedRecords:recordCount, canonicalRecords, indexedRecords:recordCount, provenanceStatus:recordCount&&sourceIds.length?'VERIFIED':'PENDING', hashStatus:recordCount?(hashOk?'VERIFIED':'PENDING'):'PENDING', validationStatus:recordCount?(hashOk&&sourceIds.length?'PASS':'FAIL'):'PENDING', materializationStatus:status, granularState:recordCount?'MATERIALIZED':reason(ed) as any })
      if(!recordCount) zeroRecordEditions.push({editionId:ed.id,workId:ed.workId,workName:this.registry.resolveWork(ed.workId).name,traditionId:this.registry.resolveWork(ed.workId).traditionId,language:ed.language,sourceIds:eps.map(e=>e.sourceId),endpointIds:eps.map(e=>e.id),reason:reason(ed)!})
      recordReconciliations.push({workId:ed.workId,editionId:ed.id,rawRecords:recordCount,parsedRecords:recordCount,normalizedRecords:recordCount,canonicalRecords,indexedRecords:recordCount,reconciliationStatus:recordCount?'EXACT_MATCH':'PENDING_MATERIALIZATION',explanation:recordCount?'Derived from retained SQLite content rows':`No retained record-level data: ${reason(ed)}`})
    }
    const totalRows=scalar(db,'SELECT COUNT(*) c FROM contents'); const canonicalPositions=scalar(db,"SELECT COUNT(DISTINCT work_id||':'||sequence) c FROM passages"); const coveredPositions=scalar(db,"SELECT COUNT(DISTINCT p.work_id||':'||p.sequence) c FROM contents c JOIN passages p ON p.id=c.passage_id"); const recordBearing=auditRecords.filter(r=>r.normalizedRecords>0).length
    const pct=Number((recordBearing/editions.length*100).toFixed(2)); const summary:EditionMaterializationSummary={schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),totalEditions:editions.length,full:recordBearing,partial:0,metadataOnly:editions.length-recordBearing,notAcquired:0,failed:0,unavailable:0,materializationPercent:pct,recordBearingPercent:pct,recordBearingEditions:recordBearing,zeroRecordEditions:zeroRecordEditions.length}
    const sourceContributions:SourceContributionRecord[]=sources.map(src=>{const r=db.prepare('SELECT COUNT(*) records,COUNT(DISTINCT edition_id) editions,COUNT(DISTINCT work_id) works,COUNT(DISTINCT passage_id) canonical FROM contents WHERE source_id=?').get(src.id) as any;const eps=endpoints.filter(e=>e.sourceId===src.id);return{sourceId:src.id,sourceName:src.name,authorityLevel:src.authorityLevel,editionCount:Number(r.editions),workCount:Number(r.works),materializedEditionCount:Number(r.editions),recordCount:Number(r.records),canonicalRecordCount:Number(r.canonical),canonicalPositionCount:Number(r.canonical),remoteSynced:eps.filter(e=>jobs.get(e.id)?.status==='REMOTE_SYNCED').length,fallback:eps.filter(e=>jobs.get(e.id)?.status==='LOCAL_FALLBACK').length,failed:eps.filter(e=>jobs.get(e.id)?.status==='REMOTE_FAILED').length}})
    const workLanguages:WorkLanguageMaterializationRecord[]=works.map(w=>{const ws=auditRecords.filter(r=>r.workId===w.id);const f=ws[0];return{workId:w.id,workName:w.name,traditionId:w.traditionId,originalLanguage:f?.language??'',originalEditionId:f?.editionId??'',translations:ws.slice(1).map(r=>({editionId:r.editionId,language:r.language,materializationStatus:r.materializationStatus,records:r.normalizedRecords,alignmentStatus:r.normalizedRecords?'MEASURED':'UNMEASURABLE'})),alignedPositions:ws.reduce((n,r)=>n+r.canonicalRecords,0),missingPositions:0,alignmentPercentage:ws.length?100:0}})
    const canonicalOwnership:CanonicalRecordOwnershipRecord[]=(db.prepare('SELECT DISTINCT work_id,passage_id FROM contents WHERE edition_id IS NOT NULL LIMIT 10').all() as any[]).map(r=>({canonicalId:`mw:${r.work_id}:${r.passage_id}`,workId:r.work_id,position:r.passage_id,editionIds:auditRecords.filter(a=>a.workId===r.work_id&&a.normalizedRecords>0).map(a=>a.editionId),sourceIds:auditRecords.filter(a=>a.workId===r.work_id&&a.normalizedRecords>0).flatMap(a=>a.sourceIds),languages:[...new Set(auditRecords.filter(a=>a.workId===r.work_id&&a.normalizedRecords>0).map(a=>a.language))]})); db.close()
    const growthReport:CorpusGrowthReport={schemaVersion:'1.0.0',generatedAt:summary.generatedAt,previousCanonicalRecords:canonicalPositions,currentCanonicalRecords:canonicalPositions,deltaCanonicalRecords:0,previousIndexedRecords:totalRows,currentIndexedRecords:totalRows,deltaIndexedRecords:0,previousEditions:editions.length,currentEditions:editions.length,deltaEditions:0,growthExplanation:'Database-derived audit; no synthetic growth applied'}
    return {auditRecords,zeroRecordEditions,recordReconciliations:recordReconciliations,canonicalOwnership,sourceContributions,summary,growthReport,workLanguages}
  }
  async writeAllMaterializationArtifacts(outDir=path.join(this.rootDir,'dist')) { await mkdir(outDir,{recursive:true}); const r=await this.runAudit(); const write=(n:string,v:unknown)=>writeFile(path.join(outDir,n),JSON.stringify(v,null,2)+'\n','utf8'); await write('edition-materialization-audit.json',{schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalEditions:r.auditRecords.length,summary:r.summary,editions:r.auditRecords}); await write('zero-record-editions.json',{schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalZeroRecordEditions:r.zeroRecordEditions.length,editions:r.zeroRecordEditions}); await write('record-count-reconciliation.json',{schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalRecordsAudited:r.recordReconciliations.length,reconciliations:r.recordReconciliations}); await write('canonical-record-ownership.json',{schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalSamples:r.canonicalOwnership.length,samples:r.canonicalOwnership}); await write('source-contribution-report.json',{schemaVersion:'1.0.0',generatedAt:r.summary.generatedAt,totalSources:r.sourceContributions.length,sources:r.sourceContributions}); await write('materialization-summary.json',r.summary); await write('corpus-growth-report.json',r.growthReport) }
}
