import { Phase18OwnershipAuditor } from '../packages/ingestion/src/depth/phase18-ownership-auditor.js'

async function main() {
  const auditor = new Phase18OwnershipAuditor(process.cwd())
  const { summary } = await auditor.runAudit()

  console.log('========================================================================')
  console.log('🔍 MOONWITNESS PHASE 18: NORMALIZED RECORD OWNERSHIP AUDITOR')
  console.log('========================================================================')
  console.log(`• Total Traditions                : ${summary.registryTotals.traditions}`)
  console.log(`• Total Works                     : ${summary.registryTotals.works}`)
  console.log(`• Total Editions                  : ${summary.registryTotals.editions}`)
  console.log(`• Total Languages                 : ${summary.registryTotals.languages}`)
  console.log(`• Total Sources                   : ${summary.registryTotals.sources}`)
  console.log(`• Total Endpoints                 : ${summary.registryTotals.endpoints}`)
  console.log('------------------------------------------------------------------------')
  console.log(`• Total Normalized Records        : ${summary.normalizedRecords.total}`)
  console.log(`• Directly Owned Records          : ${summary.normalizedRecords.owned}`)
  console.log(`• Inferred with Evidence Records  : ${summary.normalizedRecords.inferredWithEvidence}`)
  console.log(`• Unresolved Records              : ${summary.normalizedRecords.unresolved}`)
  console.log(`• Ownership Coverage Percent      : ${summary.normalizedRecords.coveragePercent}%`)
  console.log('------------------------------------------------------------------------')
  console.log(`• Measured Editions               : ${summary.editionMeasurement.measuredEditions}`)
  console.log(`• Positive Record Editions        : ${summary.editionMeasurement.positiveRecordEditions}`)
  console.log(`• Zero Record Editions            : ${summary.editionMeasurement.zeroRecordEditions}`)
  console.log(`• Unmeasurable Editions           : ${summary.editionMeasurement.unmeasurableEditions}`)
  console.log('------------------------------------------------------------------------')
  console.log(`• Distribution Sample Size        : ${summary.distributionSample.sampleSize}`)
  console.log(`• Min Records                     : ${summary.distributionSample.min}`)
  console.log(`• Max Records                     : ${summary.distributionSample.max}`)
  console.log(`• Mean Records                    : ${summary.distributionSample.mean}`)
  console.log(`• Median Records                  : ${summary.distributionSample.median}`)
  console.log(`• P25 Records                     : ${summary.distributionSample.p25}`)
  console.log(`• P50 Records                     : ${summary.distributionSample.p50}`)
  console.log(`• P75 Records                     : ${summary.distributionSample.p75}`)
  console.log(`• P90 Records                     : ${summary.distributionSample.p90}`)
  console.log(`• Distribution Sanity             : ${summary.distributionSample.sanityCheck ? 'PASS' : 'FAIL'}`)
  console.log('------------------------------------------------------------------------')
  console.log(`• Measured Unique Text Payloads   : ${summary.uniquePayloadMeasurement.globalMeasuredUniquePayloads}`)
  console.log(`• Hardcoded Corpus Metrics        : ${summary.integrityAudit.hardcodedCorpusMetrics}`)
  console.log(`• Synthetic Multipliers           : ${summary.integrityAudit.syntheticMultipliers}`)
  console.log(`• Actual SQL Aggregations         : ${summary.integrityAudit.actualSqlAggregations}`)
  console.log(`• Audit Status                    : ${summary.integrityAudit.status}`)
  console.log('========================================================================')
  console.log('✨ All Phase 18 record ownership artifacts written to dist/')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
