import { createRequire } from 'node:module'
import { existsSync } from 'node:fs'
import { readdir } from 'node:fs/promises'
import path from 'node:path'
import { UniversalCorpusRegistry } from '../packages/ingestion/src/registry/universal-registry.js'
import { MaterializationAuditor } from '../packages/ingestion/src/materialization/materialization-auditor.js'

const require=createRequire(import.meta.url)
async function main(){
  const root=process.cwd(); const registry=await new UniversalCorpusRegistry(path.join(root,'config')).loadAll(); const audit=await new MaterializationAuditor(root).runAudit(); const retained=new Set(existsSync(path.join(root,'dist/acquisition-payloads'))?await readdir(path.join(root,'dist/acquisition-payloads')):[]); const db=new(require('node:sqlite').DatabaseSync)(path.join(root,'dist/corpus.sqlite'))
  const inventory=registry.getEditions().map(ed=>{const a=audit.auditRecords.find(x=>x.editionId===ed.id)!;const eps=registry.getEndpoints().filter(e=>e.workId===ed.workId&&(!e.editionId||e.editionId===ed.id));const payloadAvailable=a.normalizedRecords>0;const reason=payloadAvailable?undefined:(eps.length?'PAYLOAD_NOT_RETAINED':'NO_ENDPOINT');return{editionId:ed.id,workId:ed.workId,traditionId:registry.resolveWork(ed.workId).traditionId,languageId:ed.language,sourceId:a.sourceIds[0],endpointIds:eps.map(e=>e.id),locators:eps.map(e=>e.url??e.repoUrl??e.baseUrl).filter(Boolean),acquisitionState:a.acquisitionStatus,payloadAvailable,parsed:a.parsedRecords>0,recordCount:a.normalizedRecords,materializationState:a.materializationStatus,measurementState:a.normalizedRecords>0?'MEASURED':'UNMEASURABLE',failureReason:reason,retainedPayload:a.normalizedRecords>0||[...retained].some(f=>a.rawSha256&&f.startsWith(a.rawSha256))}})
  const rootCauses=Object.fromEntries(inventory.filter(x=>x.failureReason).reduce((m,x)=>(m.set(x.failureReason!, (m.get(x.failureReason!)??0)+1),m),new Map<string,number>())); const count=(sql:string)=>Number((db.prepare(sql).get() as any).c); const result={schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),flow:'registry -> endpoint -> acquisition -> payload retention -> parsing -> normalization -> hashing -> provenance -> edition association -> measurement',states:{registered:inventory.length,acquired:inventory.filter(x=>x.acquisitionState!=='UNCONFIGURED').length,payloadAvailable:inventory.filter(x=>x.payloadAvailable).length,parsed:inventory.filter(x=>x.parsed).length,recordBearing:inventory.filter(x=>x.recordCount>0).length,normalized:inventory.filter(x=>x.recordCount>0).length,measured:inventory.filter(x=>x.measurementState==='MEASURED').length,canonicallyAligned:count("SELECT COUNT(DISTINCT edition_id) c FROM contents WHERE edition_id IS NOT NULL AND passage_id IS NOT NULL"),unmeasurable:inventory.filter(x=>x.recordCount===0).length},rootCauses,inventory}; db.close(); await import('node:fs/promises').then(fs=>fs.writeFile(path.join(root,'dist/phase22-acquisition-audit.json'),JSON.stringify(result,null,2)+'\n')); console.log(JSON.stringify({states:result.states,rootCauses},null,2))
}
main().catch(err=>{console.error(err);process.exitCode=1})
