import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { deterministicJsonl } from '@moonwitness/corpus-ingestion'
import type { CorpusRecord } from '@moonwitness/corpus-core'

const root = process.cwd()
const lanes = [
  { key: 'english_rwwad', lang: 'en', id: 'quranenc-english-rwwad', label: 'QuranEnc English — Rowwad Translation Center', artifact: 'mw:artifact:quranenc:english-rwwad', provenance: 'mw:provenance:quranenc:english-rwwad', sourceSha: 'a1f0320a9ba31e0457708b9c6a18700e566b469bd7e598d73ec5ca709ef4a5d8', sourceSize: 19524 },
  { key: 'indonesian_affairs', lang: 'id', id: 'quranenc-indonesian-kemenag', label: 'QuranEnc Indonesian — Kementerian Agama', artifact: 'mw:artifact:quranenc:indonesian-kemenag', provenance: 'mw:provenance:quranenc:indonesian-kemenag', sourceSha: 'e84cc21a85abb441d39a5ce19438129feb38ddee3d8fc96142b00443a83a7851', sourceSize: 19529 }
] as const
for (const lane of lanes) {
  const expression = `mw:expression:quran:${lane.lang}-${lane.id}`; const edition = `mw:edition:quran:${lane.id}`
  const records: CorpusRecord[] = [{ id: expression, record_type: 'resource', kind: 'textual.expression', extensions: { textual: { language: lane.lang, script: 'Latn', work: 'mw:work:quran' } } }, { id: edition, record_type: 'resource', kind: 'textual.edition', extensions: { textual: { edition_statement: lane.label, expressions: [expression] } } }, { id: lane.artifact, record_type: 'resource', kind: 'textual.artifact', labels: [{ value: lane.label, role: 'preferred', language: lane.lang }], extensions: { source: { artifact: lane.artifact, provenance: lane.provenance, descriptor: { availability: 'bundled', byte_size: lane.sourceSize, locations: [`https://quranenc.com/api/v1/translation/sura/${lane.key}`], media_type: 'application/json', retrieved_at: '2026-08-27T00:00:00Z', sha256: lane.sourceSha }, language: lane.lang, rights: { attribution: 'QuranEnc.com; publisher named by translation lane', license_expression: 'CC-BY-3.0', note: 'QuranEnc terms require unchanged content, attribution, version retention, and updates.', redistribution: 'permitted', status: 'licensed' } }, textual: { represents: edition } } }, { id: lane.provenance, record_type: 'provenance', source: lane.artifact, source_reference: `QuranEnc API translation/${lane.key}; source-preserving terms`, activities: [{ type: 'acquisition', method: 'Pinned per-surah API JSON responses with SHA-256 recipe inputs', software: { name: 'scripts/materialize-quranenc.ts', version: '1' }, ended_at: '2026-08-27T00:00:00Z' }] }] as CorpusRecord[]
  for (let sura = 1; sura <= 114; sura++) { const payload = JSON.parse(await readFile(path.join(root, `ingestion/recipes/quranenc/source/${lane.key}/${sura}.json`), 'utf8')) as { result: Array<{ aya: string; translation: string; footnotes?: string }> }; for (const row of payload.result) { const ayah = Number(row.aya); const target = `mw:passage:quran:${sura}:${ayah}`; records.push({ id: `mw:content:quran:${sura}:${ayah}:${lane.lang}-quranenc`, record_type: 'resource', kind: 'textual.content', extensions: { source: { artifact: lane.artifact, provenance: lane.provenance }, textual: { language: lane.lang, representation: 'source', script: 'Latn', target, text: row.translation }, ...(row.footnotes ? { quranenc: { footnotes: row.footnotes } } : {}) } } as CorpusRecord) } }
  const dataset = `datasets/${lane.id}`; const dir = path.join(root, dataset, 'data/core'); await mkdir(path.join(dir, 'resources'), { recursive: true }); await mkdir(path.join(dir, 'provenance'), { recursive: true }); await writeFile(path.join(dir, 'resources', `${lane.id}.jsonl`), deterministicJsonl(records.filter(r => r.record_type === 'resource')), 'utf8'); await writeFile(path.join(dir, 'provenance', `${lane.id}.jsonl`), deterministicJsonl(records.filter(r => r.record_type === 'provenance')), 'utf8')
  const files = [`${dataset}/data/core/provenance/${lane.id}.jsonl`, `${dataset}/data/core/resources/${lane.id}.jsonl`, `${dataset}/manifest.json`, `${dataset}/README.md`]; const checksums = await Promise.all(files.map(async file => `${createHash('sha256').update(await readFile(path.join(root, file))).digest('hex')}  ${file}`)); await writeFile(path.join(root, dataset, 'CHECKSUMS.sha256'), `${checksums.join('\n')}\n`, 'utf8'); console.log(`${lane.id}: ${records.length} records`)
}
