import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { deterministicJsonl } from '@moonwitness/corpus-ingestion'
import type { CorpusRecord } from '@moonwitness/corpus-core'

const root = process.cwd(); const dataset = 'datasets/bible-tsi-2021'; const artifact = 'mw:artifact:bible:tsi-2021-vpl'; const provenance = 'mw:provenance:bible:tsi-2021'; const expression = 'mw:expression:bible:id-tsi-2021'; const edition = 'mw:edition:bible:tsi-2021'
const source = await readFile(path.join(root, 'ingestion/recipes/tsi/source/ind_vpl.txt'), 'utf8'); const sourceBytes = Buffer.byteLength(source); const sourceSha = createHash('sha256').update(source).digest('hex')
const related = new Map<string, string[]>()
const webPassages = new Set<string>()
for (const line of (await readFile(path.join(root, 'datasets/web-classic-2020/data/core/resources/web-classic-2020.jsonl'), 'utf8')).trim().split(/\r?\n/u)) { const row = JSON.parse(line) as { id: string }; if (row.id.startsWith('mw:passage:web-classic:2020:')) webPassages.add(row.id) }
for (const line of (await readFile(path.join(root, 'datasets/bible-passage-alignments/data/core/resources/alignments.jsonl'), 'utf8')).trim().split(/\r?\n/u)) { const row = JSON.parse(line) as { extensions?: { textual?: { sources?: Array<{ target: string }>; targets?: Array<{ target: string }> } } }; const text = row.extensions?.textual; const web = text?.targets?.[0]?.target; const sourceTarget = text?.sources?.[0]?.target; if (web && sourceTarget) (related.get(web) ?? (related.set(web, []), related.get(web)!)).push(sourceTarget) }
const records: CorpusRecord[] = [
  { id: expression, record_type: 'resource', kind: 'textual.expression', extensions: { textual: { language: 'id', script: 'Latn', work: 'mw:work:bible:web-classic' } } },
  { id: edition, record_type: 'resource', kind: 'textual.edition', extensions: { textual: { edition_statement: 'Alkitab Terjemahan Sederhana Indonesia, Edisi Ketiga (2021)', expressions: [expression] } } },
  { id: artifact, record_type: 'resource', kind: 'textual.artifact', labels: [{ value: 'TSI 2021 verse-per-line export', role: 'preferred', language: 'id' }], extensions: { source: { artifact, provenance, descriptor: { availability: 'bundled', byte_size: sourceBytes, locations: ['https://ebible.org/Scriptures/ind_vpl.zip'], media_type: 'text/plain', retrieved_at: '2026-08-27T00:00:00Z', sha256: sourceSha }, institution: 'mw:institution:ebible', language: 'id', revision: '2021 TSI VPL export', rights: { attribution: 'Yayasan Alkitab BahasaKita (Albata) and Pioneer Bible Translators International', license_expression: 'CC-BY-SA-4.0', note: 'eBible.org terms require copyright/source information and same-license redistribution; changes must be identified.', redistribution: 'permitted', status: 'licensed' }, script: 'Latn', title: 'Alkitab Terjemahan Sederhana Indonesia, Edisi Ketiga' }, textual: { media_type: 'text/plain', representation_kind: 'verse_per_line_text', represents: edition } } },
  { id: provenance, record_type: 'provenance', source: artifact, source_reference: 'eBible.org ind_vpl.zip, TSI 2021, extracted ind_vpl.txt', activities: [{ type: 'acquisition', method: 'Pinned eBible VPL export and SHA-256 verified text snapshot', software: { name: 'scripts/materialize-tsi.ts', version: '1' }, ended_at: '2026-08-27T00:00:00Z' }] }
] as CorpusRecord[]
for (const line of source.split(/\r?\n/u)) { const match = /^([A-Z0-9]+) (\d+):(\d+) (.*)$/u.exec(line); if (!match) continue; const [, book, chapter, verse, text] = match; const target = `mw:passage:web-classic:2020:${book.toLowerCase()}:${chapter}:${verse}`; if (!webPassages.has(target)) continue; const content = `mw:content:bible:tsi-2021:${book.toLowerCase()}:${chapter}:${verse}`; records.push({ id: content, record_type: 'resource', kind: 'textual.content', extensions: { source: { artifact, provenance }, textual: { language: 'id', representation: 'source', script: 'Latn', target, text } } } as CorpusRecord); records.push({ id: `mw:alignment:tsi-web:${book.toLowerCase()}:${chapter}:${verse}`, record_type: 'resource', kind: 'textual.alignment', extensions: { textual: { method: 'Exact book/chapter/verse join; no semantic or textual identity asserted.', provenance, relation: 'corresponding_passage', sources: [{ target: content }], targets: [{ target }] } } } as CorpusRecord); for (const relatedTarget of related.get(target) ?? []) records.push({ id: `mw:alignment:tsi-related:${book.toLowerCase()}:${chapter}:${verse}:${relatedTarget.replaceAll(':', '-')}`, record_type: 'resource', kind: 'textual.alignment', extensions: { textual: { method: 'Inherited exact WEB passage bridge from pinned Bible alignment dataset; no semantic or textual identity asserted.', provenance, relation: 'corresponding_passage', sources: [{ target: content }], targets: [{ target: relatedTarget }] } } } as CorpusRecord) }
const base = path.join(root, dataset, 'data/core'); await mkdir(path.join(base, 'resources'), { recursive: true }); await mkdir(path.join(base, 'provenance'), { recursive: true }); await writeFile(path.join(base, 'resources', 'tsi-2021.jsonl'), deterministicJsonl(records.filter(r => r.record_type === 'resource')), 'utf8'); await writeFile(path.join(base, 'provenance', 'tsi-2021.jsonl'), deterministicJsonl(records.filter(r => r.record_type === 'provenance')), 'utf8')
const files = [`${dataset}/data/core/provenance/tsi-2021.jsonl`, `${dataset}/data/core/resources/tsi-2021.jsonl`, `${dataset}/manifest.json`, `${dataset}/README.md`]; const checksums = await Promise.all(files.map(async file => `${createHash('sha256').update(await readFile(path.join(root, file))).digest('hex')}  ${file}`)); await writeFile(path.join(root, dataset, 'CHECKSUMS.sha256'), `${checksums.join('\n')}\n`, 'utf8'); console.log(`materialized ${records.length} TSI records from ${sourceSha}`)
