import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { deterministicJsonl } from '@moonwitness/corpus-ingestion'
import type { CorpusRecord } from '@moonwitness/corpus-core'

const root = process.cwd(); const dataset = 'datasets/dhammapada-indonesian-wikisource'; const artifact = 'mw:artifact:dhammapada:indonesian-wikisource'; const provenance = 'mw:provenance:dhammapada:indonesian-wikisource'; const source = await readFile(path.join(root, 'ingestion/recipes/dhammapada-indonesian-wikisource/source/Dhammapada.wikitext'), 'utf8'); const sourceSha = createHash('sha256').update(source).digest('hex')
const normalizedSource = source.replaceAll(/^\* (\d+)\)/gmu, '* ($1)'); const headings: Array<{ offset: number; chapter: number }> = []; const headingPattern = /^== [^=].*? ==\s*$/gmu; let heading: RegExpExecArray | null; while ((heading = headingPattern.exec(normalizedSource))) headings.push({ offset: heading.index, chapter: headings.length + 1 })
const records: CorpusRecord[] = [{ id: 'mw:institution:wikimedia', record_type: 'entity', kind: 'institution', labels: [{ value: 'Wikimedia Foundation / Wikisource', role: 'preferred', language: 'en', script: 'Latn' }] }, { id: 'mw:expression:dhammapada:id-wikisource', record_type: 'resource', kind: 'textual.expression', extensions: { textual: { language: 'id', script: 'Latn', work: 'mw:work:dhammapada' } } }, { id: 'mw:edition:dhammapada:id-wikisource', record_type: 'resource', kind: 'textual.edition', extensions: { textual: { edition_statement: 'Dhammapada Bahasa Indonesia — Wikisumber', expressions: ['mw:expression:dhammapada:id-wikisource'] } } }, { id: artifact, record_type: 'resource', kind: 'textual.artifact', labels: [{ value: 'Dhammapada Bahasa Indonesia Wikisumber revision 198106', role: 'preferred', language: 'id' }], extensions: { source: { artifact, provenance, descriptor: { availability: 'bundled', byte_size: Buffer.byteLength(source), locations: ['https://id.wikisource.org/wiki/Dhammapada'], media_type: 'text/plain', retrieved_at: '2026-08-27T00:00:00Z', sha256: sourceSha }, institution: 'mw:institution:wikimedia', language: 'id', revision: 'Wikisource revision 198106', rights: { attribution: 'Wikisource contributors; Wikimedia Foundation', license_expression: 'CC-BY-SA-4.0', note: 'Wikisource content is redistributed under CC BY-SA; retain attribution and identify changes.', redistribution: 'permitted', status: 'licensed' }, script: 'Latn', title: 'Dhammapada Bahasa Indonesia' }, textual: { media_type: 'text/plain', representation_kind: 'wikitext_revision', represents: 'mw:edition:dhammapada:id-wikisource' } } }, { id: provenance, record_type: 'provenance', source: artifact, source_reference: 'id.wikisource.org revision 198106', activities: [{ type: 'acquisition', method: 'Pinned MediaWiki API wikitext revision and parsed numbered stanzas', software: { name: 'scripts/materialize-dhammapada-indonesian-wikisource.ts', version: '1' }, ended_at: '2026-08-27T00:00:00Z' }] }] as CorpusRecord[]
const stanzaPattern = /^\* \((\d+)\) ([\s\S]*?)(?=\n\* \(\d+\)|\n== |$)/gmu; const counters = new Map<number, number>(); let match: RegExpExecArray | null; while ((match = stanzaPattern.exec(normalizedSource))) { const chapter = [...headings].reverse().find(item => item.offset < match!.index)?.chapter ?? 1; const stanza = (counters.set(chapter, (counters.get(chapter) ?? 0) + 1), counters.get(chapter)!); const number = Number(match[1]); const text = match[2].replaceAll(/\[\[[^\]|]+\|([^\]]+)\]\]/gu, '$1').replaceAll(/\[\[([^\]]+)\]\]/gu, '$1').replaceAll("'''", '').replaceAll("''", '').replaceAll(/\s+/gu, ' ').trim(); const target = `mw:passage:dhammapada:${chapter}:${number}`; const content = `mw:content:dhammapada:${chapter}:${number}:id-wikisource`; records.push({ id: content, record_type: 'resource', kind: 'textual.content', extensions: { source: { artifact, provenance }, textual: { language: 'id', representation: 'source', script: 'Latn', target, text } } } as CorpusRecord); records.push({ id: `mw:alignment:dhammapada:id-wikisource-sujato:${chapter}:${number}`, record_type: 'resource', kind: 'textual.alignment', extensions: { textual: { method: 'Chapter/stanza number correspondence only; no semantic or textual identity asserted.', provenance, relation: 'corresponding_passage', sources: [{ target: content }], targets: [{ target }] } } } as CorpusRecord) }
const contentCount = records.filter(record => 'kind' in record && record.kind === 'textual.content').length
if (contentCount !== 422) throw new Error(`Expected 422 Dhammapada stanzas, got ${contentCount}`)
const base = path.join(root, dataset, 'data/core'); await mkdir(path.join(base, 'entities'), { recursive: true }); await mkdir(path.join(base, 'resources'), { recursive: true }); await mkdir(path.join(base, 'provenance'), { recursive: true }); await writeFile(path.join(base, 'entities', 'dhammapada-indonesian.jsonl'), deterministicJsonl(records.filter(r => r.record_type === 'entity')), 'utf8'); await writeFile(path.join(base, 'resources', 'dhammapada-indonesian.jsonl'), deterministicJsonl(records.filter(r => r.record_type === 'resource')), 'utf8'); await writeFile(path.join(base, 'provenance', 'dhammapada-indonesian.jsonl'), deterministicJsonl(records.filter(r => r.record_type === 'provenance')), 'utf8')
const files = [`${dataset}/data/core/entities/dhammapada-indonesian.jsonl`, `${dataset}/data/core/provenance/dhammapada-indonesian.jsonl`, `${dataset}/data/core/resources/dhammapada-indonesian.jsonl`, `${dataset}/manifest.json`, `${dataset}/README.md`]; const checksums = await Promise.all(files.map(async file => `${createHash('sha256').update(await readFile(path.join(root, file))).digest('hex')}  ${file}`)); await writeFile(path.join(root, dataset, 'CHECKSUMS.sha256'), `${checksums.join('\n')}\n`, 'utf8'); console.log(`materialized ${records.length} Wikisource Dhammapada records`)
