import { CorpusDepthAuditor } from '../packages/ingestion/src/depth/depth-auditor.js'

async function main() {
  const auditor = new CorpusDepthAuditor(process.cwd())
  const { summary, dbIntegrityAudit, sqlProvenance, indexComposition, dataModelLimitations } = await auditor.runAudit()

  console.log('========================================================================')
  console.log('📊 MOONWITNESS PHASE 16: SEMANTIC ACCOUNTING REPORT')
  console.log('========================================================================')
  console.log(`Measurement Integrity : ${dbIntegrityAudit.measurementIntegrity}`)
  console.log(`Traditions            : ${summary.totals.traditions}`)
  console.log(`Works                 : ${summary.totals.works}`)
  console.log(`Editions              : ${summary.totals.editions}`)
  console.log(`Languages             : ${summary.totals.languages}`)
  console.log(`Sources               : ${summary.totals.sources}`)
  console.log(`Endpoints             : ${summary.totals.endpoints}`)
  console.log('------------------------------------------------------------------------')
  console.log(`Canonical Positions   : ${summary.corpus.canonicalPositions}`)
  console.log(`Edition Records       : ${summary.corpus.editionRecords}`)
  console.log(`Indexed Records       : ${summary.corpus.indexedRecords}`)
  console.log('------------------------------------------------------------------------')
  console.log(`Materialization vs Measurement Accounting:`)
  console.log(`  Materialized Editions : ${summary.materialization.materializedEditions}`)
  console.log(`  Measured Editions     : ${summary.measurement.measuredEditions}`)
  console.log(`  Unmeasurable (local)  : ${summary.measurement.unmeasurableEditions}`)
  console.log(`  Zero-Record Editions  : ${summary.measurement.zeroRecordEditions}`)
  console.log(`  Positive-Record Eds   : ${summary.measurement.positiveRecordEditions}`)
  console.log(`  Invariant (zero + positive === measured) : ${summary.measurement.zeroRecordEditions + summary.measurement.positiveRecordEditions === summary.measurement.measuredEditions ? 'YES' : 'NO'}`)
  console.log(`  Invariant (measured + unmeasurable === total): ${summary.measurement.measuredEditions + summary.measurement.unmeasurableEditions === summary.totals.editions ? 'YES' : 'NO'}`)
  console.log('------------------------------------------------------------------------')
  console.log(`Distribution Sample (over ${summary.distributionSample.sampleSize} measured editions):`)
  console.log(`  Min: ${summary.distributionSample.min}, Max: ${summary.distributionSample.max}, Mean: ${summary.distributionSample.mean}, Median: ${summary.distributionSample.median}`)
  console.log(`  P25: ${summary.distributionSample.p25}, P50: ${summary.distributionSample.p50}, P75: ${summary.distributionSample.p75}, P90: ${summary.distributionSample.p90}`)
  console.log(`  Sanity Check (min <= p25 <= median <= p75 <= p90 <= max): ${summary.distributionSample.sanityCheck ? 'YES' : 'NO'}`)
  console.log('------------------------------------------------------------------------')
  console.log(`Payload Measurement:`)
  console.log(`  Measured Unique Payloads : ${summary.payloadMeasurement.measuredUniquePayloads}`)
  console.log(`  Unmeasured Editions      : ${summary.payloadMeasurement.unmeasuredEditions}`)
  console.log(`  Global Unique Payloads   : ${summary.payloadMeasurement.globalUniquePayloads === null ? 'null (PARTIAL_MEASUREMENT)' : summary.payloadMeasurement.globalUniquePayloads}`)
  console.log('------------------------------------------------------------------------')
  console.log(`Data Model Limitation Note:`)
  console.log(`  Status         : ${dataModelLimitations.editionLevelOwnership.status}`)
  console.log(`  Reason         : ${dataModelLimitations.reason}`)
  console.log(`  Recommendation : ${dataModelLimitations.recommendation}`)
  console.log('------------------------------------------------------------------------')
  console.log(`SQL Measurement Provenance (${sqlProvenance.length} verified queries):`)
  for (const sp of sqlProvenance) {
    console.log(`  • ${sp.metric.padEnd(16)}: ${String(sp.result).padStart(8)} [${sp.table}]`)
  }
  console.log('========================================================================')
}

main().catch(err => {
  console.error('Fatal error during DB-truth reporting:', err)
  process.exit(1)
})
