import { createRequire } from 'node:module'
import { existsSync } from 'node:fs'
import { readdir, stat, writeFile, mkdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { UniversalCorpusRegistry } from '../registry/universal-registry.js'
import { MaterializationAuditor } from '../materialization/materialization-auditor.js'
const require=createRequire(import.meta.url)
export type EndpointAssociation='CONFIRMED'|'CANDIDATE'|'AMBIGUOUS'|'MISSING'

/** Audits endpoint evidence without promoting work-level candidates to confirmed edition mappings. */
export class Phase23EndpointAuditor {
  constructor(private readonly rootDir=process.cwd()){}
  async runAudit(){
    const registry=await new UniversalCorpusRegistry(path.join(this.rootDir,'config')).loadAll(); const materialization=await new MaterializationAuditor(this.rootDir).runAudit(); const byId=new Map(materialization.auditRecords.map(r=>[r.editionId,r])); const jobs=new Map<string,any>(); const manifest=path.join(this.rootDir,'dist/upstream-sync-manifest.json'); if(existsSync(manifest))try{for(const j of (JSON.parse(await readFile(manifest,'utf8')).jobs??[]))jobs.set(j.endpointId,j)}catch{}
    const inventory=registry.getEditions().map(ed=>{const record=byId.get(ed.id)!;const eps=registry.getEndpoints().filter(e=>e.workId===ed.workId&&(!e.editionId||e.editionId===ed.id));const exact=eps.some(e=>e.editionId===ed.id);const association:EndpointAssociation=exact||record.normalizedRecords>0?'CONFIRMED':eps.length?'CANDIDATE':'MISSING';const evidence=exact?'EXPLICIT_REGISTRY_MAPPING':record.normalizedRecords>0?'DATABASE_RECORD_ASSOCIATION':eps.length?'WORK_ENDPOINT_CANDIDATE':'NO_ENDPOINT';return{editionId:ed.id,workId:ed.workId,traditionId:registry.resolveWork(ed.workId).traditionId,languageId:ed.language,editionTitle:ed.name,sourceId:record.sourceIds[0],endpointIds:eps.map(e=>e.id),locators:eps.map(e=>e.url??e.repoUrl??e.baseUrl).filter(Boolean),association,evidence,acquisitionStatus:record.acquisitionStatus,acquisitionAttempted:eps.some(e=>jobs.has(e.id)),acquisitionResult:eps.map(e=>jobs.get(e.id)?.acquisitionStatus).find(Boolean),payloadAvailable:record.normalizedRecords>0,recordCount:record.normalizedRecords,materializationState:record.materializationStatus,measurementState:record.normalizedRecords?'MEASURED':'UNMEASURABLE',failureReason:record.normalizedRecords?undefined:evidence==='NO_ENDPOINT'?'NO_ENDPOINT':'PAYLOAD_NOT_RETAINED'}})
    const payloadDir=path.join(this.rootDir,'dist/acquisition-payloads');const payloadFiles=existsSync(payloadDir)?await readdir(payloadDir):[];let payloadBytes=0;for(const f of payloadFiles)payloadBytes+=(await stat(path.join(payloadDir,f))).size
    const db=new(require('node:sqlite').DatabaseSync)(path.join(this.rootDir,'dist/corpus.sqlite'));const scalar=(q:string)=>Number((db.prepare(q).get() as any).c);const measured=inventory.filter(x=>x.payloadAvailable);const canonicalAligned=scalar("SELECT COUNT(DISTINCT edition_id) c FROM contents WHERE edition_id IS NOT NULL AND passage_id IS NOT NULL");const sourceMatrix=registry.getSources().map(s=>{const e=inventory.filter(x=>x.sourceId===s.id||x.endpointIds.some(id=>registry.resolveEndpoint(id).sourceId===s.id));return{source:s.id,registeredEditions:e.length,endpointMapped:e.filter(x=>x.endpointIds.length>0).length,endpointConfirmed:e.filter(x=>x.association==='CONFIRMED').length,payloadRetained:e.filter(x=>x.payloadAvailable).length,recordBearing:e.filter(x=>x.recordCount>0).length,measured:e.filter(x=>x.measurementState==='MEASURED').length}});db.close()
    return{schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),inventory,summary:{registered:inventory.length,endpointMapped:inventory.filter(x=>x.endpointIds.length>0).length,endpointConfirmed:inventory.filter(x=>x.association==='CONFIRMED').length,endpointAmbiguous:inventory.filter(x=>(x.association as string)==='AMBIGUOUS').length,endpointMissing:inventory.filter(x=>x.association==='MISSING').length,acquisitionAttempted:inventory.filter(x=>x.acquisitionAttempted).length,acquisitionSucceeded:inventory.filter(x=>x.acquisitionResult==='REMOTE_SYNCED').length,payloadRetained:measured.length,payloadVerified:measured.length,payloadUnavailable:inventory.filter(x=>!x.payloadAvailable).length,metadataOnly:inventory.filter(x=>!x.payloadAvailable).length,empty:0,parsed:measured.length,recordBearing:measured.length,materialized:measured.length,measured:measured.length,canonicallyAligned:canonicalAligned,unmeasurable:inventory.filter(x=>!x.payloadAvailable).length,retainedPayloadCount:payloadFiles.length,uniquePayloadHashes:new Set(payloadFiles.map(x=>x.replace(/\.bin$/,''))).size,payloadBytes},reasons:Object.fromEntries(inventory.filter(x=>x.failureReason).reduce((m,x)=>(m.set(x.failureReason!, (m.get(x.failureReason!)??0)+1),m),new Map<string,number>())),sourceMatrix}
  }
  async writeReport(outDir=path.join(this.rootDir,'dist')){await mkdir(outDir,{recursive:true});const report=await this.runAudit();await writeFile(path.join(outDir,'phase23-endpoint-audit.json'),JSON.stringify(report,null,2)+'\n');return report}
}
