import { createRequire } from 'node:module'
import { existsSync, readFile } from 'node:fs'
import path from 'node:path'
import { UniversalCorpusRegistry } from '../registry/universal-registry.js'
import { MaterializationAuditor } from '../materialization/materialization-auditor.js'
const require = createRequire(import.meta.url)

export type Phase21DepthReason = 'SINGLE_EDITION'|'SINGLE_LANGUAGE'|'SINGLE_SOURCE'|'LOW_RECORD_COVERAGE'|'LOW_CANONICAL_COVERAGE'|'PARTIAL_OWNERSHIP'|'UNMEASURABLE_EDITION'
export interface Phase21WorkDepth { workId:string; editionCount:number; acquiredEditionCount:number; materializedEditionCount:number; recordBearingEditionCount:number; measuredEditionCount:number; registeredLanguages:number; materializedLanguages:number; measuredLanguages:number; sourceCount:number; materializedSourceCount:number; measuredSourceCount:number; canonicalCoverage:number; reasons:Phase21DepthReason[]; shallow:boolean }

/** Phase 21 depth model. Every counter is derived from registry facts plus retained SQLite rows. */
export class Phase21DepthAuditor {
  private readonly rootDir:string; private readonly registry:UniversalCorpusRegistry
  constructor(rootDir=process.cwd()){this.rootDir=rootDir;this.registry=new UniversalCorpusRegistry(path.join(rootDir,'config'))}
  async runAudit(){
    const dbPath=path.join(this.rootDir,'dist/corpus.sqlite'); if(!existsSync(dbPath)) throw new Error(`FAIL-CLOSED: ${dbPath} is required`)
    await this.registry.loadAll(); const mat=await new MaterializationAuditor(this.rootDir).runAudit(); const db=new(require('node:sqlite').DatabaseSync)(dbPath)
    const rows=db.prepare("SELECT work_id,COUNT(*) records,COUNT(DISTINCT edition_id) measured_editions,COUNT(DISTINCT language) measured_languages,COUNT(DISTINCT source_id) measured_sources,COUNT(DISTINCT passage_id) canonical FROM contents WHERE edition_id IS NOT NULL GROUP BY work_id").all() as any[]; const byWork=new Map(rows.map(r=>[r.work_id,r]));
    const workDepth:Phase21WorkDepth[]=this.registry.getWorks().map(w=>{const eds=this.registry.getEditions().filter(e=>e.workId===w.id), eps=this.registry.getEndpoints().filter(e=>e.workId===w.id), measured=mat.auditRecords.filter(e=>e.workId===w.id&&e.normalizedRecords>0), r=byWork.get(w.id), langs=new Set(eds.map(e=>e.language)), matLangs=new Set(measured.map(e=>e.language)), sources=new Set(eps.map(e=>e.sourceId)), matSources=new Set(measured.flatMap(e=>e.sourceIds)); const reasons:Phase21DepthReason[]=[]; if(eds.length===1)reasons.push('SINGLE_EDITION');if(langs.size===1)reasons.push('SINGLE_LANGUAGE');if(sources.size<=1)reasons.push('SINGLE_SOURCE');if(!r||Number(r.records)===0)reasons.push('UNMEASURABLE_EDITION');if(r&&Number(r.canonical)===0)reasons.push('LOW_CANONICAL_COVERAGE');if(r&&Number(r.records)>0&&Number(r.records)>0&&Number(r.records)<eds.length)reasons.push('LOW_RECORD_COVERAGE'); const acquired=mat.auditRecords.filter(e=>e.workId===w.id&&e.acquisitionStatus!=='UNCONFIGURED').length; return{workId:w.id,editionCount:eds.length,acquiredEditionCount:acquired,materializedEditionCount:measured.length,recordBearingEditionCount:measured.length,measuredEditionCount:measured.length,registeredLanguages:langs.size,materializedLanguages:matLangs.size,measuredLanguages:matLangs.size,sourceCount:sources.size,materializedSourceCount:matSources.size,measuredSourceCount:matSources.size,canonicalCoverage:Number(r?.canonical??0),reasons,shallow:reasons.length>=2}})
    const totals={registeredEditions:mat.summary.totalEditions,acquiredEditions:mat.auditRecords.filter(e=>e.acquisitionStatus!=='UNCONFIGURED').length,materializedEditions:mat.summary.recordBearingEditions,recordBearingEditions:mat.summary.recordBearingEditions,measuredEditions:mat.summary.recordBearingEditions,unmeasurableEditions:mat.summary.zeroRecordEditions,materializationRate:mat.summary.materializationPercent,measurementRate:mat.summary.recordBearingPercent,canonicalPositions:Number((db.prepare("SELECT COUNT(DISTINCT work_id||':'||sequence) c FROM passages").get() as any).c),coveredPositions:Number((db.prepare("SELECT COUNT(DISTINCT p.work_id||':'||p.sequence) c FROM contents c JOIN passages p ON p.id=c.passage_id").get() as any).c)}; db.close(); return{schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),totals,works:{total:workDepth.length,shallow:workDepth.filter(w=>w.shallow).length,deep:workDepth.filter(w=>!w.shallow).length},workDepth,unmeasurableReasons:Object.fromEntries(mat.zeroRecordEditions.reduce((m,r)=>(m.set(r.reason,(m.get(r.reason)??0)+1),m),new Map<string,number>())),shallowReasons:Object.fromEntries(workDepth.flatMap(w=>w.reasons).reduce((m,r)=>(m.set(r,(m.get(r)??0)+1),m),new Map<Phase21DepthReason,number>()))}
  }
}
